name = "worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

routes = [
  
  { pattern = "collection.linefriends.com.c6k7ql9g5b.workers.dev", custom_domain = true },  
  { pattern = "ava.game.naver.com.c6k7ql9g5b.workers.dev", custom_domain = true },

  ]

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
